name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
        arch:
          - x64
          - x86
    
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
        submodules: true

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        vsversion: 2022

    - uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8.0.x

    - name: Build detours
      run: nmake
      working-directory: detours

    - name: Build and publish withdll
      if: ${{ matrix.arch == 'x64' }}
      working-directory: withdll
      run: dotnet publish -r win-x64 -c Release -o "%GITHUB_WORKSPACE%\withdll\bin.x64"

    - uses: actions/upload-artifact@main
      with:
        name: detours-${{ matrix.arch }}
        path: |
          detours/bin.${{ matrix.arch }}/syelogd.exe
          detours/bin.${{ matrix.arch }}/syelogd.pdb
          detours/bin.${{ matrix.arch }}/trcapi*.dll
          detours/bin.${{ matrix.arch }}/trcapi*.pdb
          detours/bin.${{ matrix.arch }}/trcmem*.dll
          detours/bin.${{ matrix.arch }}/trcmem*.pdb
          detours/bin.${{ matrix.arch }}/trcreg*.dll
          detours/bin.${{ matrix.arch }}/trcreg*.pdb
          detours/bin.${{ matrix.arch }}/trcssl*.dll
          detours/bin.${{ matrix.arch }}/trcssl*.pdb
          detours/bin.${{ matrix.arch }}/trctcp*.dll
          detours/bin.${{ matrix.arch }}/trctcp*.pdb

    - uses: actions/upload-artifact@main
      with:
        name: withdll
        path: |
          withdll/bin.x64/withdll.exe
          withdll/bin.x64/withdll.pdb
      if: ${{ matrix.arch == 'x64' }}
